static const char *TEMPLATE =
    "/*\n"
    "*   This file is part of Luma3DS\n"
    "*   Copyright (C) 2016-2023 Aurora Wright, TuxSH\n"
    "*/\n"
    "\n"
    "#include \"config.h\"\n"
    "#include \"emunand.h\"\n"
    "#include \"fs.h\"\n"
    "#include \"firm.h\"\n"
    "#include \"utils.h\"\n"
    "#include \"exceptions.h\"\n"
    "#include \"draw.h\"\n"
    "#include \"buttons.h\"\n"
    "#include \"pin.h\"\n"
    "#include \"crypto.h\"\n"
    "#include \"memory.h\"\n"
    "#include \"deliver_arg.h\"\n"
    "#include \"screen.h\"\n"
    "#include \"i2c.h\"\n"
    "#include \"fmt.h\"\n"
    "#include \"fatfs/sdmmc/sdmmc.h\"\n"
    "\n"
    "extern u8 __itcm_start__[], __itcm_lma__[], __itcm_bss_start__[], __itcm_end__[];\n"
    "\n"
    "extern CfgData configData;\n"
    "extern ConfigurationStatus needConfig;\n"
    "\n"
    "bool isSdMode;\n"
    "char launchedPathForFatfs[256];\n"
    "u16 launchedPath[80+1];\n"
    "BootType bootType;\n"
    "\n"
    "u16 mcuFwVersion;\n"
    "u8 mcuConsoleInfo[9];\n"
    "\n"
    "void main(int argc, char **argv, u32 magicWord)\n"
    "{\n"
    "    bool isFirmProtEnabled = true,\n"
    "         isSafeMode = false,\n"
    "         needToInitSd = false,\n"
    "         isNoForceFlagSet = false,\n"
    "         isInvalidLoader = false,\n"
    "         isNtrBoot = false;\n"
    "    FirmwareType firmType = NATIVE_FIRM;\n"
    "    FirmwareSource nandType = FIRMWARE_SYSNAND;\n"
    "    u32 emunandIndex = 0;\n"
    "\n"
    "    const vu8 *bootMediaStatus = (const vu8 *)0x1FFFE00C;\n"
    "    const vu32 *bootPartitionsStatus = (const vu32 *)0x1FFFE010;\n"
    "    u32 firmlaunchTidLow = 0;\n"
    "\n"
    "    //Shell closed, no error booting NTRCARD, NAND paritions not even considered\n"
    "    isNtrBoot = bootMediaStatus[3] == 2 && !bootMediaStatus[1] && !bootPartitionsStatus[0] && !bootPartitionsStatus[1];\n"
    "\n"
    "    if((magicWord & 0xFFFF) == 0xBEEF && argc >= 1) //Normal (B9S) boot\n"
    "    {\n"
    "        bootType = isNtrBoot ? B9SNTR : B9S;\n"
    "        strncpy(launchedPathForFatfs, argv[0], sizeof(launchedPathForFatfs) - 1);\n"
    "        launchedPathForFatfs[sizeof(launchedPathForFatfs) - 1] = 0;\n"
    "\n"
    "        u32 i;\n"
    "        for(i = 0; i < sizeof(launchedPath)/2 - 1 && argv[0][i] != 0; i++) //Copy and convert the path to UTF-16\n"
    "            launchedPath[i] = argv[0][i];\n"
    "        launchedPath[i] = 0;\n"
    "    }\n"
    "    else if(magicWord == 0xBABE && argc == 2) //Firmlaunch\n"
    "    {\n"
    "        bootType = FIRMLAUNCH;\n"
    "\n"
    "        u32 i;\n"
    "        u16 *p = (u16 *)argv[0];\n"
    "        for(i = 0; i < sizeof(launchedPath)/2 - 1 && p[i] != 0; i++)\n"
    "        {\n"
    "            launchedPath[i] = p[i];\n"
    "            launchedPathForFatfs[i] = (u8)p[i]; // UCS-2 to ascii. Meh.\n"
    "        }\n"
    "        launchedPath[i] = 0;\n"
    "\n"
    "        for(i = 0; i < 8; i++)\n"
    "            firmlaunchTidLow = (argv[1][2 * i] > '9' ? argv[1][2 * i] - 'a' + 10 : argv[1][2 * i] - '0') | (firmlaunchTidLow << 4);\n"
    "    }\n"
    "    else if(magicWord == 0xB002) //FIRM/NTRCARD boot\n"
    "    {\n"
    "        if(isNtrBoot) bootType = NTR;\n"
    "        else\n"
    "        {\n"
    "            const char *path;\n"
    "            if(!((vu8 *)bootPartitionsStatus)[2])\n"
    "            {\n"
    "                bootType = FIRM0;\n"
    "                path = \"firm0:\";\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                bootType = FIRM1;\n"
    "                path = \"firm1:\";\n"
    "            }\n"
    "\n"
    "            for(u32 i = 0; i < 7; i++) //Copy and convert the path to UTF-16\n"
    "                launchedPath[i] = path[i];\n"
    "            strcpy(launchedPathForFatfs, path);\n"
    "        }\n"
    "\n"
    "        setupKeyslots();\n"
    "    }\n"
    "    else isInvalidLoader = true;\n"
    "\n"
    "    // Set up the additional sections, overwrites argc\n"
    "    memcpy(__itcm_start__, __itcm_lma__, __itcm_bss_start__ - __itcm_start__);\n"
    "    memset(__itcm_bss_start__, 0, __itcm_end__ - __itcm_bss_start__);\n"
    "    I2C_init();\n"
    "\n"
    "    u8 mcuFwVerHi = I2C_readReg(I2C_DEV_MCU, 0) - 0x10;\n"
    "    u8 mcuFwVerLo = I2C_readReg(I2C_DEV_MCU, 1);\n"
    "    mcuFwVersion = ((u16)mcuFwVerHi << 16) | mcuFwVerLo;\n"
    "\n"
    "    // Check if fw is older than factory. See https://www.3dbrew.org/wiki/MCU_Services#MCU_firmware_versions for a table\n"
    "    if (mcuFwVerHi < 1) error(\"Unsupported MCU FW version %d.%d.\", (int)mcuFwVerHi, (int)mcuFwVerLo);\n"
    "\n"
    "    I2C_readRegBuf(I2C_DEV_MCU, 0x7F, mcuConsoleInfo, 9);\n"
    "\n"
    "    if(isInvalidLoader) error(\"Launched using an unsupported loader.\");\n"
    "\n"
    "    installArm9Handlers();\n"
    "\n"
    "    if(memcmp(launchedPath, u\"sdmc\", 8) == 0)\n"
    "    {\n"
    "        if(!mountSdCardPartition(true)) error(\"Failed to mount SD.\");\n"
    "        isSdMode = true;\n"
    "    }\n"
    "    else if(memcmp(launchedPath, u\"nand\", 8) == 0)\n"
    "    {\n"
    "        if(!remountCtrNandPartition(true)) error(\"Failed to mount CTRNAND.\");\n"
    "        isSdMode = false;\n"
    "    }\n"
    "    else if(bootType == NTR || memcmp(launchedPath, u\"firm\", 8) == 0)\n"
    "    {\n"
    "        if(mountSdCardPartition(true)) isSdMode = true;\n"
    "        else if(remountCtrNandPartition(true)) isSdMode = false;\n"
    "        else error(\"Failed to mount SD and CTRNAND.\");\n"
    "\n"
    "        if(bootType == NTR)\n"
    "        {\n"
    "            while(HID_PAD & NTRBOOT_BUTTONS);\n"
    "            loadHomebrewFirm(0);\n"
    "            mcuPowerOff();\n"
    "        }\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        char mountPoint[5];\n"
    "\n"
    "        u32 i;\n"
    "        for(i = 0; i < 4 && launchedPath[i] != u':'; i++)\n"
    "            mountPoint[i] = (char)launchedPath[i];\n"
    "        mountPoint[i] = 0;\n"
    "\n"
    "        error(\"Launched from an unsupported location: %s.\", mountPoint);\n"
    "    }\n"
    "\n"
    "    detectAndProcessExceptionDumps();\n"
    "\n"
    "    //Attempt to read the configuration file\n"
    "    needConfig = readConfig() ? MODIFY_CONFIGURATION : CREATE_CONFIGURATION;\n"
    "\n"
    "    //Determine if this is a firmlaunch boot\n"
    "    if(bootType == FIRMLAUNCH)\n"
    "    {\n"
    "        if(needConfig == CREATE_CONFIGURATION) mcuPowerOff();\n"
    "\n"
    "        switch(firmlaunchTidLow & 0xF)\n"
    "        {\n"
    "            case 2:\n"
    "                firmType = (FirmwareType)((firmlaunchTidLow >> 8) & 0xF);\n"
    "                break;\n"
    "            case 3:\n"
    "                firmType = SAFE_FIRM;\n"
    "                break;\n"
    "            case 1:\n"
    "                firmType = SYSUPDATER_FIRM;\n"
    "                break;\n"
    "        }\n"
    "\n"
    "        nandType = (FirmwareSource)BOOTCFG_NAND;\n"
    "        emunandIndex = BOOTCFG_EMUINDEX;\n"
    "        isFirmProtEnabled = !BOOTCFG_NTRCARDBOOT;\n"
    "\n"
    "        goto boot;\n"
    "    }\n"
    "\n"
    "    firmType = NATIVE_FIRM;\n"
    "    isFirmProtEnabled = bootType != NTR;\n"
    "\n"
    "    //Get pressed buttons\n"
    "    u32 pressed = HID_PAD;\n"
    "\n"
    "    //If it's a MCU reboot, try to force boot options\n"
    "    if(CFG_BOOTENV && needConfig != CREATE_CONFIGURATION)\n"
    "    {\n"
    "        u32 bootenv = CFG_BOOTENV;\n"
    "        bool validTlnc = bootenv == 3 && hasValidTlncAutobootParams();\n"
    "\n"
    "        if (validTlnc)\n"
    "            needToInitSd = true;\n"
    "\n"
    "        //Always force a SysNAND boot when quitting AGB_FIRM\n"
    "        if(bootenv == 7)\n"
    "        {\n"
    "            nandType = FIRMWARE_SYSNAND;\n"
    "\n"
    "            // Prevent multiple boot options-forcing\n"
    "            // This bit is a bit weird. Basically, as you return to HOME Menu by pressing either\n"
    "            // the HOME or POWER button, nandType will be overridden to \"SysNAND\" (needed). But,\n"
    "            // if you reboot again (e.g. via Rosalina menu), it'll use your default settings.\n"
    "            if(nandType != BOOTCFG_NAND) isNoForceFlagSet = true;\n"
    "\n"
    "            goto boot;\n"
    "        }\n"
    "\n"
    "        // Configure homebrew autoboot (if deliver arg ends up not containing anything)\n"
    "        if (bootenv == 1 && MULTICONFIG(AUTOBOOTMODE) != 0)\n"
    "            configureHomebrewAutoboot();\n"
    "\n"
    "        /* Force the last used boot options if doing autolaunch from TWL, or unless a button is pressed\n"
    "           or the no-forcing flag is set */\n"
    "        if(validTlnc || !(pressed || BOOTCFG_NOFORCEFLAG))\n"
    "        {\n"
    "            nandType = (FirmwareSource)BOOTCFG_NAND;\n"
    "            emunandIndex = BOOTCFG_EMUINDEX;\n"
    "\n"
    "            goto boot;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    u32 pinMode = MULTICONFIG(PIN);\n"
    "    bool shouldLoadConfigMenu = needConfig == CREATE_CONFIGURATION || ((pressed & (BUTTON_SELECT | BUTTON_L1)) == BUTTON_SELECT);\n"
    "    bool pinExists = pinMode != 0 && verifyPin(pinMode);\n"
    "\n"
    "    /* If the PIN has been verified, wait to make it easier to press the SAFE_MODE combo or the configuration menu button\n"
    "       (if not already pressed, for the latter) */\n"
    "    if(pinExists && !shouldLoadConfigMenu)\n"
    "    {\n"
    "        while(HID_PAD & PIN_BUTTONS);\n"
    "        wait(2000ULL);\n"
    "\n"
    "        //Update pressed buttons\n"
    "        pressed = HID_PAD;\n"
    "    }\n"
    "\n"
    "    shouldLoadConfigMenu = needConfig == CREATE_CONFIGURATION || ((pressed & (BUTTON_SELECT | BUTTON_L1)) == BUTTON_SELECT);\n"
    "    if(shouldLoadConfigMenu)\n"
    "    {\n"
    "        configMenu(pinExists, pinMode);\n"
    "\n"
    "        //Update pressed buttons\n"
    "        pressed = HID_PAD;\n"
    "    }\n"
    "\n"
    "    if(!CFG_BOOTENV && pressed == SAFE_MODE)\n"
    "    {\n"
    "        nandType = FIRMWARE_SYSNAND;\n"
    "\n"
    "        isSafeMode = true;\n"
    "        needToInitSd = true;\n"
    "\n"
    "        goto boot;\n"
    "    }\n"
    "\n"
    "    u32 splashMode = MULTICONFIG(SPLASH);\n"
    "\n"
    "    if(splashMode == 1 && loadSplash()) pressed = HID_PAD;\n"
    "\n"
    "    bool autoBootEmu = CONFIG(AUTOBOOTEMU);\n"
    "\n"
    "    if((pressed & (BUTTON_START | BUTTON_L1)) == BUTTON_START)\n"
    "    {\n"
    "        loadHomebrewFirm(0);\n"
    "        pressed = HID_PAD;\n"
    "    }\n"
    "    else if((((pressed & SINGLE_PAYLOAD_BUTTONS) || (!autoBootEmu && (pressed & DPAD_BUTTONS))) && !(pressed & (BUTTON_L1 | BUTTON_R1))) ||\n"
    "            (((pressed & L_PAYLOAD_BUTTONS) || (autoBootEmu && (pressed & DPAD_BUTTONS))) && (pressed & BUTTON_L1))) loadHomebrewFirm(pressed);\n"
    "\n"
    "    if(splashMode == 2 && loadSplash()) pressed = HID_PAD;\n"
    "\n"
    "    //Check SAFE_MODE combo again\n"
    "    if(!CFG_BOOTENV && pressed == SAFE_MODE)\n"
    "    {\n"
    "        nandType = FIRMWARE_SYSNAND;\n"
    "\n"
    "        isSafeMode = true;\n"
    "        needToInitSd = true;\n"
    "\n"
    "        goto boot;\n"
    "    }\n"
    "\n"
    "    // Set-up autoboot\n"
    "    if (MULTICONFIG(AUTOBOOTMODE) != 0)\n"
    "        configureHomebrewAutoboot();\n"
    "\n"
    "    //If booting from CTRNAND, always use SysNAND\n"
    "    if(!isSdMode) nandType = FIRMWARE_SYSNAND;\n"
    "    else nandType = (autoBootEmu == ((pressed & BUTTON_L1) == BUTTON_L1)) ? FIRMWARE_SYSNAND : FIRMWARE_EMUNAND;\n"
    "\n"
    "    //If we're booting EmuNAND or using EmuNAND FIRM, determine which one from the directional pad buttons, or otherwise from the config\n"
    "    if(nandType == FIRMWARE_EMUNAND)\n"
    "    {\n"
    "        switch(pressed & DPAD_BUTTONS)\n"
    "        {\n"
    "            case BUTTON_UP:\n"
    "                emunandIndex = 0;\n"
    "                break;\n"
    "            case BUTTON_RIGHT:\n"
    "                emunandIndex = 1;\n"
    "                break;\n"
    "            case BUTTON_DOWN:\n"
    "                emunandIndex = 2;\n"
    "                break;\n"
    "            case BUTTON_LEFT:\n"
    "                emunandIndex = 3;\n"
    "                break;\n"
    "            default:\n"
    "                emunandIndex = MULTICONFIG(DEFAULTEMU);\n"
    "                break;\n"
    "        }\n"
    "    }\n"
    "\n"
    "boot:\n"
    "\n"
    "    //If we need to boot EmuNAND, make sure it exists\n"
    "    if(nandType != FIRMWARE_SYSNAND)\n"
    "    {\n"
    "        locateEmuNand(&nandType, &emunandIndex, true);\n"
    "        if(nandType == FIRMWARE_EMUNAND && (*(vu16 *)(SDMMC_BASE + REG_SDSTATUS0) & TMIO_STAT0_WRPROTECT) == 0) //Make sure the SD card isn't write protected\n"
    "            error(\"The SD card is locked, EmuNAND can not be used.\\nPlease turn the write protection switch off.\");\n"
    "    }\n"
    "\n"
    "    ctrNandLocation = nandType; // for CTRNAND partition\n"
    "\n"
    "    if(bootType != FIRMLAUNCH)\n"
    "    {\n"
    "        configData.bootConfig = ((bootType == NTR ? 1 : 0) << 4) | ((u32)isNoForceFlagSet << 3) | ((u32)emunandIndex << 1) | (u32)nandType;\n"
    "        writeConfig(false);\n"
    "    }\n"
    "\n"
    "    bool loadFromStorage = CONFIG(LOADEXTFIRMSANDMODULES);\n"
    "    u32 firmVersion = loadNintendoFirm(&firmType, nandType, loadFromStorage, isSafeMode);\n"
    "\n"
    "    bool doUnitinfoPatch = CONFIG(PATCHUNITINFO);\n"
    "    u32 res = 0;\n"
    "    switch(firmType)\n"
    "    {\n"
    "        case NATIVE_FIRM:\n"
    "        {\n"
    "            res = patchNativeFirm(firmVersion, nandType, loadFromStorage, isFirmProtEnabled, needToInitSd, doUnitinfoPatch);\n"
    "            break;\n"
    "        }\n"
    "        case TWL_FIRM:\n"
    "            res = patchTwlFirm(firmVersion, loadFromStorage, doUnitinfoPatch);\n"
    "            break;\n"
    "        case AGB_FIRM:\n"
    "            res = patchAgbFirm(loadFromStorage, doUnitinfoPatch);\n"
    "            break;\n"
    "        case SAFE_FIRM:\n"
    "        case SYSUPDATER_FIRM:\n"
    "        case NATIVE_FIRM1X2X:\n"
    "            res = patch1x2xNativeAndSafeFirm();\n"
    "            break;\n"
    "        case NATIVE_PROTOTYPE:\n"
    "            res = patchPrototypeNative(nandType, doUnitinfoPatch);\n"
    "            break;\n"
    "    }\n"
    "\n"
    "    if(res != 0) error(\"Failed to apply %u FIRM patch(es).\", res);\n"
    "\n"
    "    unmountPartitions();\n"
    "    if(bootType != FIRMLAUNCH) deinitScreens();\n"
    "    launchFirm(0, NULL);\n"
    "}\n";
