name: Publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and install bannertool
        run: |
          git clone --depth 1 --branch 1.2.3 https://github.com/carstene1ns/3ds-bannertool.git
          cmake -S 3ds-bannertool -B bannertool-build -DCMAKE_BUILD_TYPE=Release
          cmake --build bannertool-build -j$(nproc)
          mv bannertool-build/bannertool /usr/local/bin/bannertool

      - name: Build and install makerom
        run: |
          git clone --depth 1 --branch makerom-v0.19.0 https://github.com/3DSGuy/Project_CTR.git
          make -C Project_CTR/makerom deps
          make -C Project_CTR/makerom
          mv Project_CTR/makerom/bin/makerom /usr/local/bin/makerom

      - name: Clean potential build artifacts
        run: make clean

      - name: Build
        run: make cia

      - name: Check build
        run: |
          shopt -s failglob
          ls *.3dsx *.cia
        working-directory: build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/*.3dsx
            build/*.cia

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.3dsx
            build/*.cia
          generate_release_notes: true
