name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Clean potential build artifacts
        run: make clean

      - name: Build
        run: make cia

      - name: Check build
        run: |
          shopt -s failglob
          ls *.3dsx *.cia
        working-directory: build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.3dsx
            build/*.cia
          generate_release_notes: true
